import hashlib
import logging

import cache
import registry

logger = logging.getLogger(__name__)

class ElementStub():
    '''Contains all the necessary data to instantiate an element.'''
    name = None
    base_class = None
    params = None
    instance = None
    output = None

    def __init__(self, name, params, output):
        self.name = name
        self.base_class = registry.get_element(name)
        self.params = params
        self.output = output if isinstance(output, dict) else {'default': output}

    def process_and_pass_along(self, data=None, prev_cache_key=''):
        '''Calls the process() method in the element instance, takes the data
        returned and forwards it to the next element(s) to do the same.
        '''
        logger.debug(f'Passing data to element {self.name}...')

        # Calculate current cache key, which is based on this element's plus the
        # previous' element's cache key, since this output also depends on the
        # input (generated by the previous element)
        cache_key = None
        try:
            cache_key = hashlib.sha1((self.instance.get_cache_key() + prev_cache_key).encode('utf-8'))
        except AttributeError as ex:
            # If element doesn't define a cache key function, use hash of
            # its parameter dictionary.
            cache_key = hashlib.sha1((str(self.params) + prev_cache_key).encode('utf-8'))
        cache_key = cache_key.hexdigest()

        # Try to read data from cache. If that fails, run the data through the
        # element to process and save the output to the cache.
        output = cache.read_from_cache(cache_key)

        if output:
            logger.info(f'[{self.name}] Found and read cache.')
        else:
            logger.info(f'[{self.name}] Processing data...')
            output = self.instance.process(data)

            if not self.instance.dont_cache_output:
                cache.write_to_cache(cache_key, output)

        # Pass the output of the element down the pipeline.
        if isinstance(output, dict):
            # Output of the process method needs to be redirected to multiple
            # outputs.
            for key, val in output.items():
                logger.info(f'[{self.name}] Pipeline bifurcation: sending data to `{key}`...')
                self.output[key].process_and_pass_along(val, prev_cache_key=cache_key)
        else:
            # Output can be forwarded to the default element output.
            if self.output['default']:
                logger.debug(f'[{self.name}] Forwarding data to default output...')
                self.output['default'].process_and_pass_along(output, prev_cache_key=cache_key)
            else:
                logger.debug(f'[{self.name}] Pipeline section finished!')
